name: test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.18'

      - name: Setup System
        uses: restorecommerce/setup-system-action@v1
        with:
          backing-only: false

      - name: Install Dependencies
        run: npm ci
        working-directory: demo-shop

      - name: Import master data
        run: node import -t api_key -j master
        working-directory: demo-shop

      - name: Import identity data
        run: node import -t api_key -j identity
        working-directory: demo-shop

      - name: Import extra data
        run: node import -t api_key -j extra
        working-directory: demo-shop
