name: test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.18'

      - name: Setup System
        uses: restorecommerce/setup-system-action@v1
        with:
          backing-only: false

      - name: Install Dependencies
        run: npm ci
        working-directory: demo-shop

      - name: Import master data
        run: |
          API_KEY=$(docker logs restorecommerce_facade_srv 2>/dev/null | grep API | awk '{print $7}')
          node import.js import -t $API_KEY -j master
        working-directory: demo-shop

      - name: Import identity data
        run: |
          API_KEY=$(docker logs restorecommerce_facade_srv 2>/dev/null | grep API | awk '{print $7}')
          node import.js import -t $API_KEY -j identity
        working-directory: demo-shop

      - name: Import extra data
        run: |
          API_KEY=$(docker logs restorecommerce_facade_srv 2>/dev/null | grep API | awk '{print $7}')
          node import.js import -t $API_KEY -j extra
        working-directory: demo-shop
