name: test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '20.8.0'

      - name: Setup System
        uses: restorecommerce/setup-system-action@v1
        with:
          backing-only: false

      - name: Install Dependencies
        run: npm ci

      - name: Import system master data
        run: |
          API_KEY=$(docker logs restorecommerce_facade_srv 2>/dev/null | grep API | awk '{print $7}')
          node import.js import -t $API_KEY -d system -j master

      - name: Import system identity data
        run: |
          API_KEY=$(docker logs restorecommerce_facade_srv 2>/dev/null | grep API | awk '{print $7}')
          node import.js import -t $API_KEY -d system -j identity

      - name: Import extra data
        run: |
          API_KEY=$(docker logs restorecommerce_facade_srv 2>/dev/null | grep API | awk '{print $7}')
          node import.js import -t $API_KEY -d system -j extra
