name: test

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '20.8.0'

      - name: Setup System
        uses: restorecommerce/setup-system-action@v1
        with:
          backing-only: false

      - name: Install Dependencies
        run: npm ci

      - name: Transform all data
        run: npm run generate

      - name: Import all data
        run: npm run import
